/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package network.simulator;

import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author sona1_000
 */
public class mainFrame extends javax.swing.JFrame {

    public int choice=1;
    public int nodeNum=-1;
    public int linkNum=-1;
    public int agentNum=-1;
    public int appNum=-1;
    public Node nodeObj[]=new Node[100];
    public Link linkObj[]=new Link[100];
    public Agent agentObj[]=new Agent[100];
    public Application appObj[]=new Application[100];
    private Graphics g;
            /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel0 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 600));
        getContentPane().setLayout(null);

        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Node");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Link");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Agent");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Application");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(10, 10, 220, 23);

        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseClicked(evt);
            }
        });
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(8, 79, 1070, 470);

        javax.swing.GroupLayout jPanel0Layout = new javax.swing.GroupLayout(jPanel0);
        jPanel0.setLayout(jPanel0Layout);
        jPanel0Layout.setHorizontalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel0Layout.setVerticalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel0);
        jPanel0.setBounds(10, 40, 1070, 30);

        jPanel1.setFocusTraversalPolicyProvider(true);

        jLabel1.setText("Link Type ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Duplex-link" }));
        jComboBox2.setMaximumSize(new java.awt.Dimension(77, 20));

        jLabel2.setText("QueueType");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DropTail" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(64, 20));

        jLabel3.setText("Capacity");

        jTextField1.setText("10");
        jTextField1.setAutoscrolls(false);
        jTextField1.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel4.setText("Mbps ");

        jLabel5.setText("Propogation Delay");

        jTextField3.setText("10");
        jTextField3.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField3.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField3.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel6.setText("ms ");

        jLabel7.setText("Queue Size");

        jTextField2.setText("10");
        jTextField2.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField2.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField2.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel8.setText("From ");

        jTextField4.setText("0");
        jTextField4.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField4.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel9.setText("To");

        jTextField5.setText("1");
        jTextField5.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField5.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField5.setPreferredSize(new java.awt.Dimension(30, 20));

        jButton5.setText("Add Link");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 1070, 30);

        jLabel13.setText("Agent Type ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TCP" }));
        jComboBox4.setMaximumSize(new java.awt.Dimension(77, 20));

        jLabel15.setText("Packet Size");

        jTextField7.setText("10");
        jTextField7.setAutoscrolls(false);
        jTextField7.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField7.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField7.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel16.setText("bytes");

        jButton6.setText("Add TCP");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Agent Node");

        jTextField10.setText("0");
        jTextField10.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField10.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField10.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel12.setText("Sink Node");

        jTextField11.setText("0");
        jTextField11.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField11.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField11.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 120, 530, 30);

        jPanel3.setMaximumSize(new java.awt.Dimension(1070, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(1070, 30));

        jLabel14.setText("Application Type");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FTP" }));
        jComboBox5.setMaximumSize(new java.awt.Dimension(77, 20));

        jLabel17.setText("Start Time");

        jTextField8.setText("0");
        jTextField8.setAutoscrolls(false);
        jTextField8.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField8.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField8.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel18.setText("Stop Time");

        jButton7.setText("Set FTP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField9.setText("5");
        jTextField9.setAutoscrolls(false);
        jTextField9.setMaximumSize(new java.awt.Dimension(30, 20));
        jTextField9.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextField9.setPreferredSize(new java.awt.Dimension(30, 20));

        jLabel10.setText("On Agent");

        jTextField6.setText("0");
        jTextField6.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextField6.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField6.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 160, 510, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        choice=4;
        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton2.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setBounds(10, 40, 1070, 30);
        jPanel3.setVisible(true);
        jPanel0.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        choice=3;
        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton2.setBackground(new java.awt.Color(240, 240, 240));
        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setBounds(10, 40, 1070, 30);
        jPanel2.setVisible(true);
        jPanel0.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        choice=2;
        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setBounds(10, 40, 1070, 30);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        jPanel0.setVisible(false);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        choice=1;
        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jButton2.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel0.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDesktopPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseClicked
        // TODO add your handling code here:
        if(choice==1)
        {
            nodeButton[++nodeNum] = new JButton();
            //nodeButton[nodeNum].setIcon(new javax.swing.ImageIcon(getClass().getResource("/network/simulator/node.png"))); // NOI18N
            jDesktopPane1.add(nodeButton[nodeNum]);
            nodeButton[nodeNum].setBounds(evt.getX()-30, evt.getY()-30, 60, 60);
            nodeButton[nodeNum].setText("n"+nodeNum);
            nodeButton[nodeNum].revalidate();
            nodeObj[nodeNum] = new Node(nodeNum,evt.getX(),evt.getY());
            //jLabelNode.updateUI();
            //jLabelNode.repaint();
            System.out.println("Node Created!!"+nodeNum);
            //jToolBar1.setVisible(false);
        }
    }//GEN-LAST:event_jDesktopPane1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int from=Integer.parseInt(jTextField4.getText());
        int to=Integer.parseInt(jTextField5.getText());
        int capacity=Integer.parseInt(jTextField1.getText());
        int delay=Integer.parseInt(jTextField2.getText());
        int queueSize=Integer.parseInt(jTextField3.getText());
        String linkType=jComboBox1.getName();
        String queueType=jComboBox1.getName();
        int fromX=nodeObj[from].getX_cord();
        int fromY=nodeObj[from].getY_cord();
        int toX=nodeObj[to].getX_cord();
        int toY=nodeObj[to].getY_cord();
        drawLink(fromX,fromY,toX,toY);
        System.out.println("Link Created!!");
        linkObj[++linkNum]=new Link(linkNum,from,to,linkType,capacity,delay,queueSize,queueType);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int nodeId=Integer.parseInt(jTextField10.getText());
        int sinkNodeId=Integer.parseInt(jTextField11.getText());
        String agentType=jComboBox4.getName();
        int packetSize=Integer.parseInt(jTextField7.getText());
        ++agentNum;
        agentObj[agentNum] = new Agent(agentNum,agentType,sinkNodeId,nodeId,packetSize);
        agentLabel[agentNum] = new JLabel();
        jDesktopPane1.add(agentLabel[agentNum]);
        int nodeX=nodeObj[nodeId].getX_cord();
        int nodeY=nodeObj[nodeId].getY_cord();
        agentLabel[agentNum].setText("tcp"+agentNum);
        agentLabel[agentNum].setBounds(new Rectangle(new Point(nodeX-13,nodeY-45), agentLabel[agentNum].getPreferredSize()));  
        agentLabel[agentNum].revalidate();
        System.out.println("agent Created!!"+agentNum);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int agentId=Integer.parseInt(jTextField6.getText());
        int start=Integer.parseInt(jTextField8.getText());
        int stop=Integer.parseInt(jTextField9.getText());
        String appType=jComboBox5.getName();
        ++appNum;
        appObj[appNum] = new Application(appNum,appType,agentId,start,stop);
        appLabel[appNum] = new JLabel();
        jDesktopPane1.add(appLabel[appNum]);
        int nodeId=agentObj[agentId].getNodeId();
        int nodeX=nodeObj[nodeId].getX_cord();
        int nodeY=nodeObj[nodeId].getY_cord();
        appLabel[appNum].setText("ftp"+appNum);
        appLabel[appNum].setBounds(new Rectangle(new Point(nodeX-13,nodeY-55), appLabel[appNum].getPreferredSize()));  
        appLabel[appNum].revalidate();
        System.out.println("app Created!!"+appNum);
    }//GEN-LAST:event_jButton7ActionPerformed

    public static void drawLink(int fromX, int fromY, int toX, int toY) {
        //super.paint(g);  // fixes the immediate problem.
        //((Graphics2D)g).draw(new Line2D.Double(fromX, fromY, toX, toY));
        Graphics g = jDesktopPane1.getGraphics();
        g.drawLine( fromX, fromY,  toX, toY);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    public javax.swing.JLabel agentLabel[]=new JLabel[100];
    public javax.swing.JLabel appLabel[]=new JLabel[100];
    public javax.swing.JButton nodeButton[]=new JButton[100]; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel0;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
